default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: root
  database: artworkdb

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
